comment:
  layout: header, changes, diff, sunburst
coverage:
  round: down
  precision: 2
  ignore:
    - "src/linpack.f"
  status:
    patch:
      default:
        target: 20%
    project:
      default:
        target: 60%
