name = "odrpack95"
version = "2.1.0"
license = "MIT"
author = "HugoMVale"
maintainer = "57530119+HugoMVale@users.noreply.github.com"
copyright = "Copyright 2024, HugoMVale"

[build]
auto-executables = false
auto-examples = true
auto-tests = true
module-naming = false
link = ["openblas"]      # "blas" works in linux, but not in windows

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "default"
