name: Build and test pkg

on: [push, pull_request, workflow_dispatch]

jobs:

  # Quick test in Ubuntu
  test_quick:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: gfortran
          compiler-version: 14.2
          platform: ubuntu-latest
          extra-packages: "gcovr openblas"
      
      - name: Test debug with coverage
        run: |
          gcov --version
          fpm test --profile debug --flag "-Wno-compare-reals -Wno-unused-dummy-argument -ftrampoline-impl=heap --coverage -fprofile-abs-path"
          gcovr --filter src --cobertura-pretty --output coverage.xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false
        
  # Matrix test 
  test_matrix:
    name: ${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.compiler-version }}
    runs-on: ${{ matrix.os }}
    needs: test_quick
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gfortran]
        compiler-version: ["14.2.0", "12.2.0"]
        include:
          - os: ubuntu-latest
            extra-packages: "meson openblas"
          - os: windows-latest
            extra-packages: "meson openblas pkg-config"
          - os: macos-latest
            extra-packages: "meson openblas"
                
    steps:
      - name: Set up Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: ${{ matrix.compiler }}
          compiler-version: ${{ matrix.compiler-version }}
          platform: ${{ matrix.os }}
          extra-packages: ${{ matrix.extra-packages }}

      - name: Test Debug
        run: |
          meson setup build_debug --buildtype=debug -Dbuild_tests=true -Dbuild_examples=true
          meson compile -C build_debug
          meson test -C build_debug

      - name: Test Release
        run: |
          meson setup build_release -Dbuild_tests=true -Dbuild_examples=true
          meson compile -C build_release
          meson test -C build_release

      - name: Run Examples (Release)
        run: |
          ./build_release/example/example5
          ./build_release/c/example/example5
      