name: Build and test pkg

on: [push, pull_request]

env:
  FLAGS: "-Wno-compare-reals -Wno-unused-dummy-argument -ftrampoline-impl=heap"
  FLAGSCOV: "--coverage -fprofile-abs-path"

jobs:
  linux-gcc-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Fortran compiler
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 14 
        
      - name: Install OpenBLAS
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update 
          sudo apt-get install libopenblas-dev

      - name: Install fpm
        uses: fortran-lang/setup-fpm@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fpm-version: "v0.11.0"

      - name: Build and test
        run: |
          gfortran --version
          fpm test --profile debug --flag $FLAGS --verbose
          fpm test --profile release --flag $FLAGS --verbose
      
      - name: Generate coverage report
        run: |
          gfortran --version
          gcov --version
          pip install gcovr
          rm -rf ./build/gfortran*
          fpm test --profile debug --flag "$FLAGS $FLAGSCOV"
          gcovr --filter src --cobertura-pretty --output coverage.xml
          
      - name: Run examples
        run: |
          gfortran --version
          fpm run --example "example5" --profile release

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false

  msys2-gcc-build:
    runs-on: windows-latest
    continue-on-error: false
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install MSYS2, GFortran, fpm, OpenBLAS
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: inherit
          install: |
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-fpm
            mingw-w64-x86_64-openblas

      - name: Build and test
        run: |
          gfortran --version
          fpm test --profile debug --flag $FLAGS --verbose
          fpm test --profile release --flag $FLAGS --verbose
